using Recrd.Compilers;
using Recrd.Core.Ast;
using Recrd.Core.Interfaces;
using Xunit;

namespace Recrd.Compilers.Tests;

public class TraceabilityHeaderTests
{
    private static Session MakeSession(params IStep[] steps) =>
        new(SchemaVersion: 1,
            Metadata: new SessionMetadata("test-id", DateTimeOffset.UtcNow, "chromium",
                new ViewportSize(1280, 720), "http://localhost"),
            Variables: [],
            Steps: steps);

    private static Selector MakeSelector(SelectorStrategy strategy, string value) =>
        new([strategy], new Dictionary<SelectorStrategy, string> { [strategy] = value });

    private static ActionStep MakeClickStep() =>
        new(ActionType.Click,
            MakeSelector(SelectorStrategy.DataTestId, "submit-btn"),
            new Dictionary<string, string>());

    private static ITestCompiler CreateCompiler(string targetName) =>
        targetName == "robot-browser"
            ? new RobotBrowserCompiler()
            : new RobotSeleniumCompiler();

    [Theory]
    [InlineData("robot-browser")]
    [InlineData("robot-selenium")]
    public async Task BothFiles_FirstLineStartsWithGeneratedByRecrd(string targetName)
    {
        var compiler = CreateCompiler(targetName);
        var session = MakeSession(MakeClickStep());
        var outDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        try
        {
            var result = await compiler.CompileAsync(session, new CompilerOptions { OutputDirectory = outDir });
            foreach (var filePath in result.GeneratedFiles)
            {
                var firstLine = (await File.ReadAllLinesAsync(filePath))[0];
                Assert.StartsWith("# Generated by recrd", firstLine);
            }
        }
        finally
        {
            if (Directory.Exists(outDir)) Directory.Delete(outDir, recursive: true);
        }
    }

    [Fact]
    public async Task Header_ContainsSha256()
    {
        var compiler = new RobotBrowserCompiler();
        var session = MakeSession(MakeClickStep());
        var outDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        try
        {
            var result = await compiler.CompileAsync(session, new CompilerOptions { OutputDirectory = outDir });
            var resourcePath = result.GeneratedFiles.Single(f => f.EndsWith(".resource"));
            var firstLine = (await File.ReadAllLinesAsync(resourcePath))[0];
            Assert.Contains("SHA-256:", firstLine);
        }
        finally
        {
            if (Directory.Exists(outDir)) Directory.Delete(outDir, recursive: true);
        }
    }

    [Fact]
    public async Task Header_ContainsTargetName()
    {
        var compiler = new RobotBrowserCompiler();
        var session = MakeSession(MakeClickStep());
        var outDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        try
        {
            var result = await compiler.CompileAsync(session, new CompilerOptions { OutputDirectory = outDir });
            var resourcePath = result.GeneratedFiles.Single(f => f.EndsWith(".resource"));
            var firstLine = (await File.ReadAllLinesAsync(resourcePath))[0];
            Assert.Contains("robot-browser", firstLine);
        }
        finally
        {
            if (Directory.Exists(outDir)) Directory.Delete(outDir, recursive: true);
        }
    }

    [Fact]
    public async Task Header_ContainsTimestamp()
    {
        var compiler = new RobotBrowserCompiler();
        var session = MakeSession(MakeClickStep());
        var outDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        try
        {
            var result = await compiler.CompileAsync(session, new CompilerOptions { OutputDirectory = outDir });
            var resourcePath = result.GeneratedFiles.Single(f => f.EndsWith(".resource"));
            var firstLine = (await File.ReadAllLinesAsync(resourcePath))[0];
            // ISO 8601 contains "T" and either "Z" or "+"
            Assert.True(firstLine.Contains("T") && (firstLine.Contains("Z") || firstLine.Contains("+")),
                $"Header does not contain ISO 8601 timestamp. Line: {firstLine}");
        }
        finally
        {
            if (Directory.Exists(outDir)) Directory.Delete(outDir, recursive: true);
        }
    }
}
