using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Recrd.Core.Ast;
using Recrd.Core.Serialization;

namespace Recrd.Compilers.Internal;

internal static class HeaderEmitter
{
    internal static string Emit(string targetName, string? sourceFilePath, Session? session)
    {
        var version = Assembly.GetExecutingAssembly().GetName().Version?.ToString(3) ?? "0.0.0";
        var timestamp = DateTimeOffset.UtcNow.ToString("o");

        byte[] bytes;
        string sourceLabel;

        if (sourceFilePath != null && File.Exists(sourceFilePath))
        {
            bytes = File.ReadAllBytes(sourceFilePath);
            sourceLabel = sourceFilePath;
        }
        else if (session != null)
        {
            var json = JsonSerializer.Serialize(session, RecrdJsonContext.Default.Session);
            bytes = Encoding.UTF8.GetBytes(json);
            sourceLabel = "in-memory";
        }
        else
        {
            bytes = [];
            sourceLabel = "in-memory";
        }

        var hashBytes = SHA256.HashData(bytes);
        var sha256hex = Convert.ToHexString(hashBytes).ToLowerInvariant();

        // Single header line containing all traceability info so tests can assert on line[0]
        return $"# Generated by recrd {version} at {timestamp} for target {targetName} source: {sourceLabel} SHA-256: {sha256hex}";
    }
}
